/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabelaPrecosRouteImport } from './routes/tabela-precos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PainelVendedoresRouteImport } from './routes/painel-vendedores'
import { Route as PainelExecutivoRouteImport } from './routes/painel-executivo'
import { Route as EstoquePrecosRouteImport } from './routes/estoque-precos'
import { Route as CalculadoraPrecoRouteImport } from './routes/calculadora-preco'
import { Route as CadastroPrestadorRouteImport } from './routes/cadastro-prestador'
import { Route as AcertoDescontoRouteImport } from './routes/acerto-desconto'
import { Route as IndexRouteImport } from './routes/index'

const TabelaPrecosRoute = TabelaPrecosRouteImport.update({
  id: '/tabela-precos',
  path: '/tabela-precos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelVendedoresRoute = PainelVendedoresRouteImport.update({
  id: '/painel-vendedores',
  path: '/painel-vendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelExecutivoRoute = PainelExecutivoRouteImport.update({
  id: '/painel-executivo',
  path: '/painel-executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoquePrecosRoute = EstoquePrecosRouteImport.update({
  id: '/estoque-precos',
  path: '/estoque-precos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraPrecoRoute = CalculadoraPrecoRouteImport.update({
  id: '/calculadora-preco',
  path: '/calculadora-preco',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroPrestadorRoute = CadastroPrestadorRouteImport.update({
  id: '/cadastro-prestador',
  path: '/cadastro-prestador',
  getParentRoute: () => rootRouteImport,
} as any)
const AcertoDescontoRoute = AcertoDescontoRouteImport.update({
  id: '/acerto-desconto',
  path: '/acerto-desconto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerto-desconto': typeof AcertoDescontoRoute
  '/cadastro-prestador': typeof CadastroPrestadorRoute
  '/calculadora-preco': typeof CalculadoraPrecoRoute
  '/estoque-precos': typeof EstoquePrecosRoute
  '/painel-executivo': typeof PainelExecutivoRoute
  '/painel-vendedores': typeof PainelVendedoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tabela-precos': typeof TabelaPrecosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerto-desconto': typeof AcertoDescontoRoute
  '/cadastro-prestador': typeof CadastroPrestadorRoute
  '/calculadora-preco': typeof CalculadoraPrecoRoute
  '/estoque-precos': typeof EstoquePrecosRoute
  '/painel-executivo': typeof PainelExecutivoRoute
  '/painel-vendedores': typeof PainelVendedoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tabela-precos': typeof TabelaPrecosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerto-desconto': typeof AcertoDescontoRoute
  '/cadastro-prestador': typeof CadastroPrestadorRoute
  '/calculadora-preco': typeof CalculadoraPrecoRoute
  '/estoque-precos': typeof EstoquePrecosRoute
  '/painel-executivo': typeof PainelExecutivoRoute
  '/painel-vendedores': typeof PainelVendedoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tabela-precos': typeof TabelaPrecosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerto-desconto'
    | '/cadastro-prestador'
    | '/calculadora-preco'
    | '/estoque-precos'
    | '/painel-executivo'
    | '/painel-vendedores'
    | '/sitemap.xml'
    | '/tabela-precos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerto-desconto'
    | '/cadastro-prestador'
    | '/calculadora-preco'
    | '/estoque-precos'
    | '/painel-executivo'
    | '/painel-vendedores'
    | '/sitemap.xml'
    | '/tabela-precos'
  id:
    | '__root__'
    | '/'
    | '/acerto-desconto'
    | '/cadastro-prestador'
    | '/calculadora-preco'
    | '/estoque-precos'
    | '/painel-executivo'
    | '/painel-vendedores'
    | '/sitemap.xml'
    | '/tabela-precos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcertoDescontoRoute: typeof AcertoDescontoRoute
  CadastroPrestadorRoute: typeof CadastroPrestadorRoute
  CalculadoraPrecoRoute: typeof CalculadoraPrecoRoute
  EstoquePrecosRoute: typeof EstoquePrecosRoute
  PainelExecutivoRoute: typeof PainelExecutivoRoute
  PainelVendedoresRoute: typeof PainelVendedoresRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TabelaPrecosRoute: typeof TabelaPrecosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tabela-precos': {
      id: '/tabela-precos'
      path: '/tabela-precos'
      fullPath: '/tabela-precos'
      preLoaderRoute: typeof TabelaPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-vendedores': {
      id: '/painel-vendedores'
      path: '/painel-vendedores'
      fullPath: '/painel-vendedores'
      preLoaderRoute: typeof PainelVendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-executivo': {
      id: '/painel-executivo'
      path: '/painel-executivo'
      fullPath: '/painel-executivo'
      preLoaderRoute: typeof PainelExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-precos': {
      id: '/estoque-precos'
      path: '/estoque-precos'
      fullPath: '/estoque-precos'
      preLoaderRoute: typeof EstoquePrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-preco': {
      id: '/calculadora-preco'
      path: '/calculadora-preco'
      fullPath: '/calculadora-preco'
      preLoaderRoute: typeof CalculadoraPrecoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-prestador': {
      id: '/cadastro-prestador'
      path: '/cadastro-prestador'
      fullPath: '/cadastro-prestador'
      preLoaderRoute: typeof CadastroPrestadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerto-desconto': {
      id: '/acerto-desconto'
      path: '/acerto-desconto'
      fullPath: '/acerto-desconto'
      preLoaderRoute: typeof AcertoDescontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcertoDescontoRoute: AcertoDescontoRoute,
  CadastroPrestadorRoute: CadastroPrestadorRoute,
  CalculadoraPrecoRoute: CalculadoraPrecoRoute,
  EstoquePrecosRoute: EstoquePrecosRoute,
  PainelExecutivoRoute: PainelExecutivoRoute,
  PainelVendedoresRoute: PainelVendedoresRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TabelaPrecosRoute: TabelaPrecosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
